### ISSUE TITLE
PHPFlasher in stateless API

### ISSUE THREAD

**Issue by pimjansen** [php-flasher/php-flasher#143]
Im using PHPFlasher in a symfony application however it adds session state when not in use. I am combining it with API Platform and my API itself it stateless so it should not hold any session data (causes errors).

How should i handle this (if even possible?)

**Comment by yoeunes** [comment]
Hi @pimjansen,

Thank you for bringing this issue to my attention. Indeed, it's problematic when `PHPFlasher` introduces session state in stateless APIs.

As a temporary solution until a suitable configuration option is implemented, consider overriding the `flasher.storage` service. To do this, replace the current implementation with an instance of `ArrayBag`.

Here are the relevant links:

- [`flasher.storage` service definition](https://github.com/php-flasher/php-flasher/blob/9524e40ae6849b2008791647e2b9561abf062218/src/Symfony/Resources/config/services.php#L27)
- [`ArrayBag` class](https://github.com/php-flasher/php-flasher/blob/9524e40ae6849b2008791647e2b9561abf062218/src/Prime/Storage/Bag/ArrayBag.php)

This adjustment should prevent `PHPFlasher` from maintaining a session state when it's not in use.

**Comment by pimjansen** [comment]
I wish it was but it hits Flasher\Symfony\Http\Request

**Comment by yoeunes** [comment]
Hey @pimjansen 👋,

I have just released a new version, [v1.14.0](https://github.com/php-flasher/php-flasher/releases/tag/v1.14.0), which defaults to using `ArrayBag` when sessions are disabled. Could you please upgrade to this version and let me know if it resolves your issue?

If the problem persists, would you be able to share a minimal reproducible example project on GitHub? This would be greatly helpful for me to further investigate and address the issue.

**Comment by pimjansen** [comment]
Thanks for the quick responses to start with. Will test it out tomorrow when in office! Will update with the results

**Comment by pimjansen** [comment]
@yoeunes still the same error is there. I do not have a public repo for this issue but technically it is just a symfony application with a controller that uses flasher fine. Further it has API platform installed with a stateless API.

See screenshot for the trace

![image](https://github.com/php-flasher/php-flasher/assets/1457219/307f7c28-f181-4588-aa8c-16bf8656b86d)

**Comment by yoeunes** [comment]
Hey @pimjansen,

I've just released a new version [v1.14.1](https://github.com/php-flasher/php-flasher/releases/tag/v1.14.1) to fix the error with stateless routes.

Could you please update to this new version and test it in your application? I would appreciate if you could confirm whether this version solves your issue. If you encounter any further problems, don't hesitate to let me know.

**Comment by pimjansen** [comment]
Still the same outcome:
`Session was used while the request was declared stateless.`

The problem is there since you are checking the actual request which has maybe a session active but it doesnt mean the endpoint should actually use session itself. What you can do is check the actual firewall

```
/** @var FirewallConfig $firewallConfig */
$firewallConfig = $this->firewallMap->getFirewallConfig($request);
if (!$firewallConfig->isStateless()) {
    
}
```

You can get there by injecting `FirewallMapInterface $firewallMap,`

**Comment by yoeunes** [comment]
Hi @pimjansen,

Thank you for your suggestion. I tried reproducing the issue with Symfony versions `6.0` and `6.3`, but I was unable to encounter the same problem. I inspected the stateless routes carefully and found that they were operating as expected, even when no session was present.

I'm puzzled as to why we are seeing different behaviors. There might be a specific configuration or context in your application that is causing this issue to occur. I'd need more details or ideally a minimal reproduction case that I could run on my own.

Would it be possible for you to provide a sample project or more details about the specific conditions under which the issue occurs? This would greatly help me in identifying the cause of the issue.

Here are the screenshots from my tests:
![Screenshot from 2023-06-05 12-09-37](https://github.com/php-flasher/php-flasher/assets/10859693/71a948aa-adef-4c96-b8fe-00cc417f6afc)
![Screenshot from 2023-06-05 12-10-34](https://github.com/php-flasher/php-flasher/assets/10859693/d60af74a-a2d3-47bd-af35-22d089bc0912)

**Comment by pimjansen** [comment]
Confirmed. It happens when you have a session in the application and use the swagger spec (openapi) to make the request. When that happens there a cookie active so the session is sent. 

For me this is fine though as is. The changes you did are always good for fail safe use while sessions are not active though.

**Comment by yoeunes** [comment]
Hey Pim! 👋

Great solution! 🎉 It's awesome to see that you found this elegant solution without requiring any updates to PHPFlasher. 👍 Thank you so much for sharing it!

**Comment by pimjansen** [comment]
> Hey Pim! 👋
> 
> 
> 
> Great solution! 🎉 It's awesome to see that you found this elegant solution without requiring any updates to PHPFlasher. 👍 Thank you so much for sharing it!

Well it is actually a decoration of the php flasher symfony lib where the session listener is located.

The main thing is when something is invoked on the existing domain it will always reuse the existing sessionid cookie by default even though the endpoint is stateless.

This was also the reason why you could not reproduce it since the endpoint had no stateful auth on itself. So i guess its fair to say if the url is stateless there is never need to set a session since it breaks on next request anyways
