### ISSUE TITLE
Flash message doesn't show in livewire without reloading

### ISSUE THREAD

**Issue by codebyshami** [php-flasher/php-flasher#161]
```
  public function bell()
    {
        $this->count += 1;
        flash()->addInfo('Your information has been saved and a confirmation email has been sent.');
    }

```

This flash message doesn't show up until I reload the page
If I reload the page then what's is the point of using livewire

**Comment by mugerwa96** [comment]
no updates yet for  livewire v3,  experiencing the same problem

**Comment by gaiththewolf** [comment]
### I made this solution until update come for supporting livewire 3 dispatch logic :

#### 1. add an envent listener in **app.layout.blade.php** at the **bottom** of **body**
```js
<script type="text/javascript">
    window.addEventListener('php-flasher-js', event => {
        flasher.render(JSON.parse(event.detail[0]));
    });
</script>
```
#### 2. add **Helper** function

```php
use Livewire\Component;

if (!function_exists('flashDispatch')) {
    function flashDispatch(Component $component, $message = null, $type = 'success', array $options = array(), array $stamps = array())
    {
        $flasher = flash($message, $type, $options, $stamps);
        $messages = json_encode(app('flasher.response_manager')->render([],'array'));
        $component->dispatch('php-flasher-js', $messages);
        return $flasher;
    }
}
```
#### 3. in component use like this
```php
<?php

namespace App\Livewire;

use Livewire\Component;

class Test extends Component
{
    public function test() {
        flashDispatch($this, "working fine !", 'warning');
    }

    public function render()
    {
        return view('livewire.test');
    }
}

```

**Comment by yoeunes** [comment]
Hello guys,

I've just released PHPFlasher v1.15.5 with support for Livewire v3. It's not fully tested yet, so I'd appreciate if you could test it in your environment. Please update using:

```bash
composer require php-flasher/flasher-laravel ^1.15.5
```

Let me know if there are any issues. Your feedback will help in deciding whether to close this issue.

Thanks!
Younes

**Comment by gaiththewolf** [comment]
> Hello guys,
> 
> I've just released PHPFlasher v1.15.5 with support for Livewire v3. It's not fully tested yet, so I'd appreciate if you could test it in your environment. Please update using:
> 
> ```shell
> composer require php-flasher/flasher-laravel ^1.15.5
> ```
> 
> Let me know if there are any issues. Your feedback will help in deciding whether to close this issue.
> 
> Thanks! Younes

Good job, thanks

**Comment by gaiththewolf** [comment]
> Hello guys,
> 
> I've just released PHPFlasher v1.15.5 with support for Livewire v3. It's not fully tested yet, so I'd appreciate if you could test it in your environment. Please update using:
> 
> ```shell
> composer require php-flasher/flasher-laravel ^1.15.5
> ```
> 
> Let me know if there are any issues. Your feedback will help in deciding whether to close this issue.
> 
> Thanks! Younes

there is a problem that drove me crazy 😄 , inside component i have this function : 
```php
public function resetForum()
{
    $this->dispatch('refreshListOpened');
    flash()->addSuccess("Done !");
}
```

in this form the dispatched event not received in the other component, but when i comment the flash line : 
```php
public function resetForum()
{
    $this->dispatch('refreshListOpened');
    //flash()->addSuccess("Done !");
}
```
the dispatched event received fine 😄

**Comment by yoeunes** [comment]
Hi @gaiththewolf i just released v1.15.7, this should fix the problem

**Comment by donnebanget** [comment]
> Hi @gaiththewolf i just released v1.15.7, this should fix the problem

Hi @yoeunes when using default => 'flasher' that working fine, but when using notyf as default  when change page that using wire:navigate notyf not showing.

Example:
1. User edit they profile and save (notyf showing)
2. User back to dashboard
3. User back to edit profile and save (notyf not showing) but when reload page and save again notyf showing

https://github.com/php-flasher/php-flasher/assets/26705319/6670907d-3ef4-4d17-958f-58e2fc3ff093

**Comment by yoeunes** [comment]
Hello @donnebanget, can you create a repo on github so i can reproduce the issue ?

**Comment by yoeunes** [comment]
Hello @donnebanget,

Can you please upgrade to version `v1.15.8`, as this should fix the issue. Additionally, this version includes an upgrade for the flasher assets to `v1.3.2`.

If you're not using a CDN, please ensure to manually copy the new assets into your `public/` folder. This step is crucial for the changes to take effect properly.

Best regards,
Younes

**Comment by donnebanget** [comment]
> Hello @donnebanget,
> 
> Can you please upgrade to version `v1.15.8`, as this should fix the issue. Additionally, this version includes an upgrade for the flasher assets to `v1.3.2`.
> 
> If you're not using a CDN, please ensure to manually copy the new assets into your `public/` folder. This step is crucial for the changes to take effect properly.
> 
> Best regards, Younes

Hello @yoeunes , sorry for late respond.

I have upgrade to the v.1.15.8 and i back to use cdn but this issue still persist when using notyf. when using default flasher its okay before and after upgrade.

Notes: i re-clone repository than composer upgrade

Thanks for the awesome project!

**Comment by yoeunes** [comment]
Hi @codebyshami,

I’ve released PHPFlasher v2.0, which adds support for Livewire 3 and should fix the issue you’ve reported.

I’m closing this issue now. If you still have problems after updating, feel free to reopen it or open a new one.

Thanks.
